test

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -11,19 +11,13 @@ permissions:
   contents: read
 
 jobs:
-  checkout:
-    name: Checkout Code
+  build_and_deploy:
+    name: Build and Deploy real-time flight
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
 
-  docker:
-    name: Docker Login and Build into Docker Hub
-    runs-on: ubuntu-latest
-    needs: checkout
-    continue-on-error: true
-    steps:
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with: 
@@ -38,21 +32,11 @@ jobs:
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/spark:latest
 
-  azure_login:
-    name: Connect to Azure Cloud
-    runs-on: ubuntu-latest
-    needs: checkout
-    steps:
       - name: Connect and configure Azure Cloud
         uses: azure/login@v2
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
 
-  ssh_to_azure:
-    name: SSH to Azure VM
-    runs-on: ubuntu-latest
-    needs: azure_login
-    steps:
       - name: SSH to Azure VM
         uses: appleboy/ssh-action@master
         with:
@@ -60,30 +44,37 @@ jobs:
           username: ${{ secrets.SSH_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           port: ${{ secrets.SSH_PORT }}
-
-  deploy_docker_compose:
-    name: Deploy Docker Compose to Azure VM
-    runs-on: ubuntu-latest
-    needs: ssh_to_azure
-    steps:
-      - name: Copy Docker Compose File to Azure VM
-        uses: appleboy/scp-action@master
-        with:
-          source: ./docker-compose.yml
-          target: ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}/home/azureuser
-          host: ${{ secrets.HOST }}
-          username: ${{ secrets.USERNAME }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          port: ${{ secrets.SSH_PORT }}
-
-      - name: SSH to Azure VM and Build Docker Compose
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.SSH_HOST }}
-          username: ${{ secrets.SSH_USERNAME }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          port: ${{ secrets.SSH_PORT }}
           script: |
-            cd /home/azureuser
+            # Print the current directory
+            echo "Current directory:"
+            pwd
+
+            # Print the contents of the current directory
+            echo "Directory contents:"
+            ls -la
+
+            # Use the GITHUB_WORKSPACE variable to navigate to the repository directory
+            cd $GITHUB_WORKSPACE
+
+            # Ensure Docker Compose is installed
+            if ! command -v docker-compose &> /dev/null
+            then
+                echo "docker-compose could not be found, installing..."
+                sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+                sudo chmod +x /usr/local/bin/docker-compose
+            fi
+
+            # Build and run Docker containers
             docker-compose build
             docker-compose up -d
+
+            # Ensure the Python script is present
+            if [ ! -f create_index_elastic.py ]; then
+                echo "create_index_elastic.py not found!"
+                exit 1
+            fi
+
+            python3 create_index_elastic.py
+
+            # Run Spark consumer job
+            docker-compose exec spark-master spark-submit --class consumer --total-executor-cores 4 --executor-memory 2g --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.4,org.elasticsearch:elasticsearch-spark-30_2.12:8.8.2,commons-httpclient:commons-httpclient:3.1 spark_consumer.py
